### PR TITLE
Update base_env.clj for clojure.test namespace

### PR DESCRIPTION
**Pull request by arav93**

### CODE REVIEW

**Comment by nbeloglazov** [comment]
How do you choose which functions to annotate? `clojure.test` seem to have quite a lot of functions: https://clojure.github.io/clojure/clojure.test-api.html. Or some of them already annotated?

**Comment by frenchy64** [comment]
We decided: Priority 1 is vars with :doc. Priority 2 is vars with :added metadata.

Includes macros, which we just need to unit test.

**Comment by nbeloglazov** [comment]
I see. Ambrose, do you have some script that can give you a list of all un-annotated vars in given namespace (potentially sorted them by priority). I think it shouldn't very hard to write such script.

**Comment by frenchy64** [comment]
``` clojure
(defn todo-vars [ns]
  (filter (fn [v] (when (instance? clojure.lang.Var v) 
                      (let [m (meta v)]
                        (or (:doc m) (:added m)))))
           (ns-publics (the-ns ns))))
```

Untested.

**Comment by frenchy64** [comment]
Sorry misread that. There's a command somewhere.

**Comment by frenchy64** [comment]
See bottom of this wiki. https://github.com/clojure/core.typed/wiki/clojure.core-Annotations

**Pull request merged**
